cursor-color = #efdfd6
cursor-text = #d6c3b7
background = #19120d
foreground = #efdfd6
selection-background = #e4c0a6
selection-foreground = #422b1a

palette =8=#9f8d82
palette =0=#4c4c4c

palette =1=#ac8a8c
palette =9=#c49ea0

palette =2=#8aac8b
palette =10=#9ec49f

palette =3=#aca98a
palette =11=#c4c19e

palette =4=#ffb780
palette =12=#a39ec4

palette =5=#ac8aac
palette =13=#c49ec4

palette =6=#8aacab
palette =14=#9ec3c4

palette =15=#e7e7e7
palette =7=#f0f0f0
