[colors.primary]
background = '#18120c'
foreground = '#eee0d5'
 
[colors.cursor]
text = '#eee0d5'
cursor = '#d4c4b5' 
 
[colors.vi_mode_cursor]
text = '#18120c'
cursor = '#f9bb71' 
 
[colors.search.matches]
foreground = '#504539' 
background = '#bccd9d' 
 
[colors.search.focused_match]
foreground = '#504539' 
background = '#f9bb71' 
 
[colors.footer_bar]
foreground = '#504539' 
background = '#eee0d5' 
 
[colors.hints.start]
foreground = '#504539' 
background = '#dfc1a2' 
 
[colors.hints.end]
foreground = '#504539' 
background = '#dfc1a2' 
 
[colors.selection]
text = '#18120c'
background = '#f9bb71'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#f9bb71' 
yellow = '#835414' 
blue = '#f9bb71' 
magenta = '#bccd9d' 
cyan = '#dfc1a2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
