#!/usr/bin/bash

mkdir -p ~/WorkSpace/Algorithm

./scripts/arch_only 

sudo pacman -Syyu --noconfirm

sudo pacman -S --noconfirm base-devel

sudo pacman -S --noconfirm \
    neovim \
    curl \
    i3-wm \
    vim \
    alacritty \
    fish \
    i3blocks \
    ranger \
    picom \
    npm \
    gcc \
    gdb \
    clang \
    nodejs \
    ttf-jetbrains-mono \
    ttf-jetbrains-mono-nerd \
    paru \
    yarn \
    mpv


curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

bash scripts/setup

bash scripts/install

sudo chsh -s "$(which fish)" "$USER"

sudo reboot
