#!/usr/bin/bash

mkdir -p ~/WorkSpace/Algorithm

./scripts/arch_only 

sudo pacman -Syyu --noconfirm

sudo pacman -S --noconfirm base-devel

sudo pacman -S --noconfirm \
    neovim \
    curl \
    i3-wm \
    vim \
    alacritty \
    fish \
    i3blocks \
    ranger \
    picom \
    npm \
    gcc \
    gdb \
    clang \
    nodejs \
    ttf-jetbrains-mono \
    ttf-jetbrains-mono-nerd \
    paru \
    yarn \
    mpv \
    mpd \
    ncmpcpp \
    variety \
    openssh 

plugins_dir=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins

git clone https://github.com/zsh-users/zsh-completions $plugins_dir/zsh-completions
git clone https://github.com/zsh-users/zsh-autosuggestions $plugins_dir/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $plugins_dir/zsh-syntax-highlighting
git clone https://github.com/Aloxaf/fzf-tab $plugins_dir/fzf-tab
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

bash scripts/setup

bash scripts/install

sudo chsh -s "$(which fish)" "$USER"

sudo reboot
