#!/bin/bash

rm -rf .config .i3 .vimrc

mkdir .config

sources_config=(
    ~/.config/alacritty/
    ~/.config/fish/
    ~/.config/i3blocks/
    ~/.config/nvim/
    ~/.config/ranger/
    ~/.config/picom.conf
)

sources_home=(
    ~/.i3/
    ~/.vimrc
)


cp -r "${sources_config[@]}" ./.config/

cp -r "${sources_home[@]}" .

