#!/bin/bash

rm -rf alacritty fish .i3 i3blocks nvim ranger .vimrc picom.conf

sources=(
  ~/.config/alacritty/
  ~/.config/fish/
  ~/.config/i3blocks/
  ~/.config/nvim/
  ~/.config/ranger/
  ~/.i3/
  ~/.vimrc
  ~/.config/picom.conf
)

cp -r "${sources[@]}" .

