#!/usr/bin/bash

sources_config=(
    .config/alacritty/
    .config/fish/
    .config/i3blocks/
    .config/nvim/
    .config/ranger/
    .config/picom.conf
    ~/.config/mpd/
    ~/.config/ncmpcpp
    ~/.config/dunst/
)

sources_home=(
    .vimrc
    .i3/
    .zshrc
    .p10k.zsh
)

target_config=(
    ~/.config/alacritty/
    ~/.config/fish/
    ~/.config/i3blocks/
    ~/.config/nvim/
    ~/.config/ranger/
    ~/.config/picom.conf
    ~/.config/mpd/
    ~/.config/ncmpcpp
    ~/.config/dunst/
)

target_home=(
    ~/.vimrc
    ~/.i3/
    ~/.zshrc
    .p10k.zsh
)

rm -rf "${target_config[@]}"
rm -rf "${target_home[@]}"

cp -r "${sources_config[@]}" ~/.config/
cp -r "${sources_home[@]}" ~/
