-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#19120d', -- 背景
  base01 = '#140d08', --较浅的背景色
  base02 = '#221a14',
  base03 = '#ffb780', -- 键盘字符，匹配大括号
  base04 = '#d6c3b7',
  base05 = '#ffb780', -- 括号，运算符
  base06 = '#382f28',
  base07 = '#413731',

  base08 = '#c6cb95',-- 变量名
  base09 = '#ffdcc4', -- 整数、布尔值 (True/False)。
  base0A = '#e4c0a6', --类名 (Class)、搜索匹配到的背景
  base0B = '#ffb780', -- 字符串
  base0C = '#c6cb95',
  base0D = '#6c3a08', -- 函数名
  base0E = '#e4c0a6', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#efdfd6', -- 选中文字背景
  fg = '#19120d', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9f8d82', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#c6cb95',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e4c0a6',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#89511f',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#261e18', --底边
  fg = '#ffb780',
})
