-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#121318', -- 背景
  base01 = '#0d0e13', --较浅的背景色
  base02 = '#1a1b21',
  base03 = '#b7c4ff', -- 键盘字符，匹配大括号
  base04 = '#c6c5d0',
  base05 = '#b7c4ff', -- 括号，运算符
  base06 = '#2f3036',
  base07 = '#38393f',

  base08 = '#e4bad9',-- 变量名
  base09 = '#dee1f9', -- 整数、布尔值 (True/False)。
  base0A = '#c2c5dd', --类名 (Class)、搜索匹配到的背景
  base0B = '#b7c4ff', -- 字符串
  base0C = '#e4bad9',
  base0D = '#364479', -- 函数名
  base0E = '#c2c5dd', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e3e1e9', -- 选中文字背景
  fg = '#121318', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#90909a', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e4bad9',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c2c5dd',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#4e5b92',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#1f1f25', --底边
  fg = '#b7c4ff',
})
