-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#0e1513', -- 背景
  base01 = '#090f0e', --较浅的背景色
  base02 = '#161d1b',
  base03 = '#82d5c7', -- 键盘字符，匹配大括号
  base04 = '#bec9c5',
  base05 = '#82d5c7', -- 括号，运算符
  base06 = '#2b3230',
  base07 = '#343b39',

  base08 = '#adcae5',-- 变量名
  base09 = '#cce8e2', -- 整数、布尔值 (True/False)。
  base0A = '#b1ccc6', --类名 (Class)、搜索匹配到的背景
  base0B = '#82d5c7', -- 字符串
  base0C = '#adcae5',
  base0D = '#005048', -- 函数名
  base0E = '#b1ccc6', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#dde4e1', -- 选中文字背景
  fg = '#0e1513', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#899390', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#adcae5',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b1ccc6',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#006b60',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#1a211f', --底边
  fg = '#82d5c7',
})
